custom:
  text_current: '{current} из {total}'
  text_previous: '« Предыдущий'
  text_next: 'Следующий »'
  text_close: Закрыть
  slideshow:
    text_start: 'почати слайд-шоу'
    text_stop: 'зупинити слайд-шоу'
